name: recetox-waveica-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base >= 4.1.0
  - r-waveslim
  - r-jade
  - r-corpcor
  - r-proc
  - r-plsdepot
  - r-fdrtool
  - r-scatterplot3d
  - r-ggfortify
  - r-devtools
  - r-patrick
  - r-dplyr