{% set name = "recetox-waveica" %}
{% set version = "0.2.0" %}
{% set github = "https://github.com/recetox/waveica" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 77bb6ccc4cd18e30d4ee9f3effedcc29dd9ce29b535b645ea6b6765fe8cbcd41

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/
    - lib/R/lib/
  script: R CMD INSTALL --build .

requirements:
  host:
    - r-base
    - r-waveslim
    - r-jade
    - r-corpcor
    - r-mgcv
  run:
    - r-base
    - r-waveslim
    - r-jade
    - r-corpcor
    - r-mgcv

test:
  commands:
    - $R -e "library('recetox.waveica')"

about:
  home: "{{ github }}"
  license: MIT
  summary: Removal of batch effects for large-scale untargeted metabolomics data based on wavelet transform.
    This is a customized fork of the original WaveICA package that contains both WaveICA and WaveICA 2.0.

extra:
  maintainers:
    - hechth
    - martenson
    - maximskorik
  identifiers:
    - doi:10.1016/j.aca.2019.02.010
    - doi:10.1007/s11306-021-01839-7
